# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
arr1 = np.arange(10,49)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [4]:
arr1.shape

(39,)

5. Print the type of the previous array in question 3

In [5]:
arr1.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [6]:

print(f"Version:{np.__version__} and Configuration:{np.__config__}")

Version:1.19.2 and Configuration:<module 'numpy.__config__' from 'C:\\Users\\iramn\\anaconda3\\lib\\site-packages\\numpy\\__config__.py'>


7. Print the dimension of the array in question 3


In [9]:
arr1.ndim

1

8. Create a boolean array with all the True values

In [8]:
import numpy as np
boolen_Array = np.ones((4,3),dtype =bool)
boolen_Array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

9. Create a two dimensional array




In [11]:
arr3 = np.array([[1,3,4,9,10],[12,3,6,9,8]])
arr3

array([[ 1,  3,  4,  9, 10],
       [12,  3,  6,  9,  8]])

10. Create a three dimensional array



In [12]:
arr4 = np.array([[[1,3,5,6],[9,4,6,5],[2,7,3,4]]])
arr4

array([[[1, 3, 5, 6],
        [9, 4, 6, 5],
        [2, 7, 3, 4]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [13]:
vector = np.arange(1,20)
print(f"simple vector: {vector}")
print(f"Reverse vector: {vector[::-1]}")

simple vector: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reverse vector: [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [14]:
import numpy as np
x= np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [16]:
a= np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [17]:
arr = np.array([1, 2, 3, 4, 5],dtype=float) 
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [19]:
arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

    
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [20]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr1>arr2

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [21]:
arr = np.arange(0,9)
arr[1::2]

array([1, 3, 5, 7])

18. Replace all odd numbers to -1 from previous array

In [22]:
arr[1::2]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [23]:
arr = np.arange(10)
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [24]:
arr = np.ones((5,5))
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [25]:
import numpy as np
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
np.where(arr2d==5,12,arr2d)

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [26]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0:1,:2]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [29]:
array1 = np.arange(9)
array2=np.reshape(array1,(3,3))
print(array2)
print(f"first 1st 1-D array: {array2[0]}")

[[0 1 2]
 [3 4 5]
 [6 7 8]]
first 1st 1-D array: [0 1 2]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [30]:
array1 = np.arange(10)
# array2 = np.reshape(array1,ndmin=2)
# arr2D = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
array2=np.reshape(array1,(2,5))
print(array2)
print(f"2nd value from 2nd 1-D array: {array2[1][1]}")

[[0 1 2 3 4]
 [5 6 7 8 9]]
2nd value from 2nd 1-D array: 6


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [31]:
arr2D = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
print(arr2D)
print(f"the third column but only the first two rows: {arr2D[:3,2]}")

[[0 1 2 3 4]
 [5 6 7 8 9]]
the third column but only the first two rows: [2 7]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [32]:
import numpy as np
x = np.random.randint((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[4 2]
Minimum and Maximum Values:
2 4


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [33]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("Array1: ",a)
print("Array2: ",b)
print(np.intersect1d(a, b))

Array1:  [1 2 3 2 3 4 3 4 5 6]
Array2:  [ 7  2 10  2  7  4  9  4  9  8]
[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [34]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("Array1: ",a)
print("Array2: ",b)
print(np.where(a==b))

Array1:  [1 2 3 2 3 4 3 4 5 6]
Array2:  [ 7  2 10  2  7  4  9  4  9  8]
(array([1, 3, 5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [35]:
import random 
data = np.random.randn(7, 4)
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(data[names !='Will'])   
print(names[names !='Will'])
print([names !='Will'])

[[ 6.02577266e-01  1.02687751e-03  1.00200658e+00  7.63063083e-01]
 [ 5.07265023e-01 -3.71823290e-01 -1.14879065e+00 -1.34992093e+00]
 [-9.50770778e-01 -2.59400989e-01 -8.88890531e-01 -6.23224820e-01]
 [ 2.38200073e-01  1.00832002e+00  9.65215091e-02  2.12891235e+00]
 [-1.41704425e+00  2.43983194e-01  7.10344001e-02  3.02929329e-01]]
['Bob' 'Joe' 'Bob' 'Joe' 'Joe']
[array([ True,  True, False,  True, False,  True,  True])]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [36]:
import numpy as np
import random 
data = np.random.randn(7, 4)
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

print(data[names !='Will'],data[names !='Joe'])   
print(names[names !='Will'],names[names !='Joe']) 
print([names !='Will'],[names !='Joe'])

[[ 0.65273951  0.06208883  2.08821774 -0.24880363]
 [ 0.05270643 -0.33737036  1.991317   -0.16021584]
 [ 0.99697107 -0.06837553  1.52623413 -0.69850109]
 [-1.06312558  1.82936129  1.73207001 -1.28452528]
 [-1.3959073  -0.75448119 -0.22778484  0.4309947 ]] [[ 0.65273951  0.06208883  2.08821774 -0.24880363]
 [-0.24613398  0.66504525  0.96801899 -1.52587837]
 [ 0.99697107 -0.06837553  1.52623413 -0.69850109]
 [ 0.29763622  0.81418209 -0.17255723 -0.53336332]]
['Bob' 'Joe' 'Bob' 'Joe' 'Joe'] ['Bob' 'Will' 'Bob' 'Will']
[array([ True,  True, False,  True, False,  True,  True])] [array([ True, False,  True,  True,  True, False, False])]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [37]:

import numpy as np
import random 
my_array = np.arange(1,16).reshape(3,5)
arr = np.array(my_array,dtype=float) 

print(f"2D array of shape 5x3 to contain decimal numbers :\n {arr}")

print("Dimension of Array: ",arr.ndim)

2D array of shape 5x3 to contain decimal numbers :
 [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]
Dimension of Array:  2


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [38]:
import numpy as np
import random 
my_array = np.arange(1,17).reshape(2,2,4)
arr = np.array(my_array,dtype=float) 

print(f"2D array of shape 5x3 to contain decimal numbers :\n {arr}")

print("Dimension of Array: ",arr.ndim)
print("Shape of Array: ",arr.shape)

2D array of shape 5x3 to contain decimal numbers :
 [[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]
Dimension of Array:  3
Shape of Array:  (2, 2, 4)


33. Swap axes of the array you created in Question 32

In [39]:

import numpy as np
import random 
my_array = np.arange(1,17).reshape(2,2,4)
arr = np.array(my_array,dtype=float) 

print(f"2D array of shape 5x3 to contain decimal numbers :\n {arr}")
print(f"Swap axes of the array you created in Question 32 :\n {arr.T}")
print("Dimension of Array: ",arr.ndim)
print("Shape of Array: ",arr.shape)

2D array of shape 5x3 to contain decimal numbers :
 [[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]
Swap axes of the array you created in Question 32 :
 [[[ 1.  9.]
  [ 5. 13.]]

 [[ 2. 10.]
  [ 6. 14.]]

 [[ 3. 11.]
  [ 7. 15.]]

 [[ 4. 12.]
  [ 8. 16.]]]
Dimension of Array:  3
Shape of Array:  (2, 2, 4)


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [40]:
import numpy as np
ran = np.arange(10)
squre_root = np.sqrt(ran)
x=np.where(squre_root<0.5,0,squre_root)
print(f"square root of every element in the array:\n {x}")

square root of every element in the array:
 [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [41]:
a = np.random.randint(12)
b = np.random.randint(12)
# a= np.arange(1,13)
# b= np.arange(1,13)
arr_1 = np.array(a)
arr_2 = np.array(b)

# result_no=np.maximum(a,b)
result_array=np.maximum(arr_1,arr_2)
# print(f" values of A: {a}\n values of B: {b} \n Maximum Value: {result_no}")
print(f" values of A: {arr_1}\n values of B: {arr_2} \n Maximum Value: {result_array}")

 values of A: 9
 values of B: 10 
 Maximum Value: 10


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [42]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
uniq  = np.unique(names)
print(f"unique names by using Unique Method: {uniq} ")
    
print(f"unique names by using Set : {set(names)} ")

unique names by using Unique Method: ['Bob' 'Joe' 'Will'] 
unique names by using Set : {'Will', 'Bob', 'Joe'} 


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [43]:
import numpy as np
test_list = np.array([1,2,3,4,5])
remove_list= np.array([5,6,7,8,9])

print(test_list!=remove_list)
print('\n',np.setdiff1d(test_list,remove_list))

[ True  True  True  True  True]

 [1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [44]:

import numpy as np

print("Printing Original array")

sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 

print ("sampleArray:\n",sampleArray)

print("Array after deleting column 2 on axis 1")

deleteArray = np.delete(sampleArray , 1, axis = 1) 

print ("DeleteArray:\n",deleteArray)

newColumn = np.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")

insertArray = np.insert(deleteArray , 1, newColumn, axis = 1) 

print ("InsertArray:\n",insertArray)

Printing Original array
sampleArray:
 [[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
DeleteArray:
 [[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
InsertArray:
 [[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [45]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
dot_prodct = np.dot(x,y)
print(f"Dot Product of the two matrix:\n {dot_prodct}")

Dot Product of the two matrix:
 [[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [46]:
from numpy import random

x = random.randint(20)
cum_sum = np.cumsum(x)
print("random numbers:",x)
cum_sum

random numbers: 2


array([2], dtype=int32)